apiVersion: apps/v1
kind: Deployment
metadata:
  name: biocad-devops-testing-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: avigdornir/hello_world_biocad_testing:latest
          ports:
            - containerPort: 32777

---
apiVersion: v1
kind: Service
metadata:
  name: biocad-devops-testing-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      nodePort: 32767
      port: 32777
      targetPort: 32777
